import { type NextPage } from "next";
import React, { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import Navbar from "../../../components/navbar/Navbar";
import { signIn, signOut, useSession } from "next-auth/react";
import Button, { ColorOptions } from "../../../components/buttons/Button";
import { useRouter } from "next/router";

import { api } from "../../../utils/api";
import { contextProps } from "@trpc/react-query/shared";

import { Listbox, Transition } from "@headlessui/react";
import Dialog from "./../../../components/dialogs/Dialog";
import Container from "../../../components/annonse/Container";
import Swiper from "../../../components/swiper/Swiper";
import { PencilIcon } from "@heroicons/react/24/outline";

const NyAnnonse: NextPage = () => {
  const { data: sessionData } = useSession();
  const router = useRouter();
  const ctx = api.useContext();

  // get id from nextjs router
  const { id } = router.query;

  const { data: user } = api.profile.getUser.useQuery(
    {
      id: id as string,
    },
    {
      enabled: !!id,
    }
  );

  return (
    <>
      <Head>
        <title>Toolhub | Annonser</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-[120px] flex h-screen flex-col items-center justify-center overflow-hidden bg-gray-100">
        <Navbar />
        <div className="mt-[6rem] flex h-[20rem] w-[20rem] flex-col items-center rounded-2xl bg-white shadow-md">
          <div className="flex h-[6rem] w-full flex-row items-center gap-3 rounded-md px-8">
            <div className="h-[2.5rem] w-[2.5rem] rounded-full bg-black"></div>
            <div className="flex flex-col">
              <p className="cursor-pointer text-green-700">{user?.name}</p>
              <p>{user?.phone ? user.phone : "Mangler tlf"}</p>
            </div>
          </div>
          <p>{`Epost: ${user?.email ? user?.email : "Har ikke epost"}`}</p>
        </div>
      </main>
    </>
  );
};

export default NyAnnonse;
